on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Render

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: install linux dependencies
        run: |
          sudo apt-get update 
          sudo apt-get install --fix-missing -y --no-install-recommends build-essential cmake pandoc libcurl4-openssl-dev 
    
      - name: set up R
        uses: r-lib/actions/setup-r@v2 
        
      - name: install packages
        run: R -e "install.packages(c('DHARMa', 'glmmTMB', 'performance', 'dplyr', 'lme4', 'see'), repos = 'https://cloud.r-project.org')"
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with: 
          r-version: '4.4.1'
          
      - name: fix quarto set-up issues
        run: | 
          export GITHUB_TOKEN='${{ secrets.GITHUB_TOKEN }}'
          quarto install tinytex
          
      - name: Render and Publish
        run: quarto render quantile_resid_talk.qmd
        with:
          target: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
